context:
  version: "12.6"
  name: "saxon-he"
  build: 0

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE${{ version | split(".") | join("-") }}/SaxonHE${{ version | split(".") | join("-") }}J.zip
  sha256: cbb6657da061c155476ad9e43a3564a4cc928d4951ebeed2eafe5a0aa74e2aee

build:
  number: ${{ build }}
  noarch: generic

requirements:
  run:
    - openjdk
    - if: unix
      then: __unix
    - if: win
      then: __win

tests:
  - package_contents:
      files:
        - etc/conda/activate.d/${{ name }}_activate.*
        - etc/conda/deactivate.d/${{ name }}_deactivate.*
        - ${{ "Library/" if win }}lib/SaxonHE/saxon-he-*.jar
        - ${{ "Library/" if win }}lib/SaxonHE/doc/*
        - ${{ "Library/" if win }}lib/SaxonHE/notices/*
        - ${{ "Library/" if win }}lib/SaxonHE/lib/*.jar

  - script:
      - if: unix
        then: java -cp ${CLASSPATH} net.sf.saxon.Transform -?
      - if: win
        then: java -cp %CLASSPATH% net.sf.saxon.Transform -?

about:
  homepage: http://saxon.sourceforge.net
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: "Open Source SAXON XSLT processor developed by Saxonica Limited."
  documentation: https://www.saxonica.com/documentation/index.html
  repository: https://github.com/Saxonica/Saxon-HE

extra:
  recipe-maintainers:
    - munechika-koyo
