context:
  version: "12.5"
  name: "saxon-he"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/Saxonica/Saxon-HE/releases/download/SaxonHE${{ version | split(".") | join("-") }}/SaxonHE${{ version | split(".") | join("-") }}J.zip
  sha256: 35a46728792bd4cec2fc262d48777b4c79b5cdeef03d2981e3a64ecb3a19f716

build:
  number: 0

requirements:
  run:
    - openjdk

tests:
  - package_contents:
      files:
        - etc/conda/activate.d/${{ name }}_activate.*
        - etc/conda/deactivate.d/${{ name }}_deactivate.*
        - ${{ "Library/" if win }}lib/SaxonHE/saxon-he-*.jar
        - ${{ "Library/" if win }}lib/SaxonHE/doc/*
        - ${{ "Library/" if win }}lib/SaxonHE/notices/*
        - ${{ "Library/" if win }}lib/SaxonHE/lib/*.jar

  - script:
    - if: unix
      then: java -cp ${CLASSPATH} net.sf.saxon.Transform -?
    - if: win
      then: java -cp %CLASSPATH% net.sf.saxon.Transform -?

about:
  homepage: http://saxon.sourceforge.net
  license: MPL-2.0
  license_file: LICENSE.txt
  summary: "Open Source SAXON XSLT processor developed by Saxonica Limited."
  documentation: https://www.saxonica.com/documentation/index.html
  repository: https://github.com/Saxonica/Saxon-HE

extra:
  recipe-maintainers:
    - munechika-koyo
